name: digicamscheduling
channels:
- astropy
- anaconda
- conda-forge
- defaults
- omnia
dependencies:
- astropy
- cython
- docopt
- healpy
- jupyter
- matplotlib
- numpy
- pandas
- pip
- pyyaml
- schema
- scipy
- tqdm
- pip:
  - matplotlib-label-lines
  - PyAstronomy
